
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibraryManager.EntityFramework.Model
{

using System;
    using System.Collections.Generic;
    
public partial class BookItem
{

    public string BookId { get; set; }

    public Nullable<int> Number { get; set; }

    public Nullable<int> Count { get; set; }

    public Nullable<bool> Status { get; set; }



    public virtual Book Book { get; set; }

}

}
