
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibraryManager.EntityFramework.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Book
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Book()
    {

        this.Borrows = new HashSet<Borrow>();

        this.Authors = new HashSet<Author>();

    }


    public string Id { get; set; }

    public string Title { get; set; }

    public int PublisherId { get; set; }

    public Nullable<int> YearPublish { get; set; }

    public Nullable<int> BookCategoryId { get; set; }

    public Nullable<int> PageNumber { get; set; }

    public string Size { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<bool> Status { get; set; }



    public virtual BookCategory BookCategory { get; set; }

    public virtual Publisher Publisher { get; set; }

    public virtual BookItem BookItem { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Borrow> Borrows { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Author> Authors { get; set; }

}

}
