
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibraryManager.EntityFramework.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Borrow
{

    public int Id { get; set; }

    public string BookId { get; set; }

    public string MemberId { get; set; }

    public string LibrarianId { get; set; }

    public System.DateTime BorrowDate { get; set; }



    public virtual Book Book { get; set; }

    public virtual Librarian Librarian { get; set; }

    public virtual Member Member { get; set; }

}

}
