
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibraryManager.EntityFramework.Model
{

using System;
    using System.Collections.Generic;
    
public partial class View_Book
{

    public string Id { get; set; }

    public string Title { get; set; }

    public Nullable<int> BookCategoryId { get; set; }

    public int PublisherId { get; set; }

    public Nullable<int> YearPublish { get; set; }

    public int AuthorId { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<int> PageNumber { get; set; }

    public string Size { get; set; }

    public Nullable<int> NumberOfBook { get; set; }

    public Nullable<int> Count { get; set; }

    public Nullable<bool> Status { get; set; }

}

}
