
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibraryManager.EntityFramework.Model
{

using System;
    using System.Collections.Generic;
    
public partial class View_Author
{

    public int AuthorId { get; set; }

    public string NickName { get; set; }

    public string BookId { get; set; }

    public string BookTitle { get; set; }

    public Nullable<bool> Status { get; set; }

}

}
